[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
markets = "7ALFC87zvuPvpp9h5Stq9SSP3kTCUJfhtirEZVJmZYy4"
mock_pyth_pull = "rec5EKMGg6MxZYaMdyBfgwp4d5rB9T1VQH5pJv5LtFJ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/evergreen/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
# # test-interest = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/accrue-interest.ts"
test-create-market = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/create-market.ts"
test-borrow = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/borrow.ts"

# [test.validator]
# url = "https://api.mainnet-beta.solana.com"

# [[test.validator.clone]]
# address = "DBE3N8uNjhKPRHfANdwGvCZghWXyLPdqdSbEW2XFwBiX"
# filename = "account_data.json"
# # address = "rec5EKMGg6MxZYaMdyBfgwp4d5rB9T1VQH5pJv5LtFJ"
# # address = "7UVimffxr9ow1uXYxsr4LHAcV58mLzhmwaeKvJ1pjLiE"