[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
pathfinder = "7ALFC87zvuPvpp9h5Stq9SSP3kTCUJfhtirEZVJmZYy4"
mock_pyth_pull = "rec5EKMGg6MxZYaMdyBfgwp4d5rB9T1VQH5pJv5LtFJ"
switchboard_on_demand = "7GCiue6chgGuk6BvaurQNWD1Ervho8zEdcNWt5ZCYQhu"
assistant_to_the_regional_manager = "4JpJWm53pKAwsyJ5HxGoXRwFFW8FSr49mYjkRKzn7pyj"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/eloqjava/.config/solana/id.json"
# wallet = "/home/evergreen/.config/solana/id.json"
# cluster = "devnet"
# wallet = "/home/evergreen/.config/solana/id.json"

[scripts]
# run all tests
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 'tests/{*,**/*}.ts'"

# run pathfinder tests
test-path-create-market = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/pathfinder/create-market.ts"
test-path-borrow = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/pathfinder/borrow.ts"
test-path-deposit = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/pathfinder/deposit.ts"
test-path-deposit-collateral = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/pathfinder/deposit-collateral.ts"
test-path-withdraw = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/pathfinder/withdraw.ts"
test-path-accrue-interest = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/pathfinder/accrue-interest.ts"
test-path-liquidate = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/pathfinder/liquidate.ts"
test-path-repay = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/pathfinder/repay.ts"
test-path-withdraw-collateral = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/pathfinder/withdraw-collateral.ts"
test-path-update-collateral = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/pathfinder/update-collateral.ts"
test-path-restrict-collateral = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/pathfinder/restrict-collateral.ts"
test-path-oracle = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/utils//oracle.ts"
test-path-config = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/pathfinder/config.ts"
test-path-balances = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/pathfinder/balances.ts"

# run all manager tests
test-manager = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/assistant-to-the-regional-manager/*.ts"
test-manager-queue = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/assistant-to-the-regional-manager/queue.ts"
test-manager-cap = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/assistant-to-the-regional-manager/cap.ts"
test-manager-timelock = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/assistant-to-the-regional-manager/timelock.ts"
test-manager-guardian = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/assistant-to-the-regional-manager/guardian.ts"
test-manager-roles = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/assistant-to-the-regional-manager/roles.ts"
test-manager-deposit = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/assistant-to-the-regional-manager/deposit.ts"
test-manager-fee = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/assistant-to-the-regional-manager/fee.ts"
test-manager-withdraw = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/assistant-to-the-regional-manager/withdraw.ts"