[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
markets = "7ALFC87zvuPvpp9h5Stq9SSP3kTCUJfhtirEZVJmZYy4"
mock_pyth_pull = "rec5EKMGg6MxZYaMdyBfgwp4d5rB9T1VQH5pJv5LtFJ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/evergreen/.config/solana/id.json"
# cluster = "devnet"
# wallet = "/home/evergreen/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
test-create-market = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/create-market.ts"
test-borrow = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/borrow.ts"
test-deposit = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/deposit.ts"
test-accrue-interest = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/accrue-interest.ts"
test-liquidate = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/liquidate.ts"
test-repay = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/repay.ts"
test-withdraw-collateral = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/withdraw-collateral.ts"
test-update-collateral = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/update-collateral.ts"
test-restrict-collateral = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/restrict-collateral.ts"
